### ISSUE TITLE
HElp

### ISSUE THREAD

**Issue by suprohub** [FedericoBruzzone/tdlib-rs#10]
error while loading shared libraries: libunwind.so.1: cannot open shared object file: No such file or directory

**Comment by suprohub** [comment]
message from build script

**Comment by suprohub** [comment]
libunwind.so
libunwind.so.8
libunwind.so.8.1.0

**Comment by suprohub** [comment]
i have this

**Comment by FedericoBruzzone** [comment]
Thanks for reporting this issue.
Tgt issue [32](https://github.com/FedericoBruzzone/tgt/issues/32) should fix it, for both installation via Cargo and building from source.
Let me know :D 

[32] https://github.com/FedericoBruzzone/tgt/issues/32

**Comment by suprohub** [comment]
> Thanks for reporting this issue. Tgt issue [32](https://github.com/FedericoBruzzone/tgt/issues/32) should fix it, for both installation via Cargo and building from source. Let me know :D
> 
> [32] [FedericoBruzzone/tgt#32](https://github.com/FedericoBruzzone/tgt/issues/32)

its not works

**Comment by suprohub** [comment]
same error, but now i have link

**Comment by suprohub** [comment]
lrwxrwxrwx 1 root root  27 мая 10  2024 /usr/lib64/libunwind-coredump.so -> libunwind-coredump.so.0.0.0*
lrwxrwxrwx 1 root root  27 мая 10  2024 /usr/lib64/libunwind-coredump.so.0 -> libunwind-coredump.so.0.0.0*
-rwxr-xr-x 1 root root 26K мая 10  2024 /usr/lib64/libunwind-coredump.so.0.0.0*
lrwxrwxrwx 1 root root  19 мая 10  2024 /usr/lib64/libunwind-generic.so -> libunwind-x86_64.so*
lrwxrwxrwx 1 root root  25 мая 10  2024 /usr/lib64/libunwind-ptrace.so -> libunwind-ptrace.so.0.0.0*
lrwxrwxrwx 1 root root  25 мая 10  2024 /usr/lib64/libunwind-ptrace.so.0 -> libunwind-ptrace.so.0.0.0*
-rwxr-xr-x 1 root root 23K мая 10  2024 /usr/lib64/libunwind-ptrace.so.0.0.0*
lrwxrwxrwx 1 root root  25 мая 10  2024 /usr/lib64/libunwind-setjmp.so -> libunwind-setjmp.so.0.0.0*
lrwxrwxrwx 1 root root  25 мая 10  2024 /usr/lib64/libunwind-setjmp.so.0 -> libunwind-setjmp.so.0.0.0*
-rwxr-xr-x 1 root root 13K мая 10  2024 /usr/lib64/libunwind-setjmp.so.0.0.0*
lrwxrwxrwx 1 root root  18 мая 10  2024 /usr/lib64/libunwind.so -> libunwind.so.8.1.0*
lrwxrwxrwx 1 root root  29 ноя 10 09:26 /usr/lib64/libunwind.so.1 -> /usr/lib64/libunwind.so.8.0.1
lrwxrwxrwx 1 root root  29 ноя 10 09:33 /usr/lib64/libunwind.so.1.0.0 -> /usr/lib64/libunwind.so.8.0.1
lrwxrwxrwx 1 root root  18 мая 10  2024 /usr/lib64/libunwind.so.8 -> libunwind.so.8.1.0*
-rwxr-xr-x 1 root root 62K мая 10  2024 /usr/lib64/libunwind.so.8.1.0*
lrwxrwxrwx 1 root root  25 мая 10  2024 /usr/lib64/libunwind-x86_64.so -> libunwind-x86_64.so.8.1.0*
lrwxrwxrwx 1 root root  36 ноя 10 09:26 /usr/lib64/libunwind-x86_64.so.1 -> /usr/lib64/libunwind-x86_64.so.8.0.1
lrwxrwxrwx 1 root root  36 ноя 10 09:33 /usr/lib64/libunwind-x86_64.so.1.0.0 -> /usr/lib64/libunwind-x86_64.so.8.0.1
lrwxrwxrwx 1 root root  25 мая 10  2024 /usr/lib64/libunwind-x86_64.so.8 -> libunwind-x86_64.so.8.1.0*
-rwxr-xr-x 1 root root 70K мая 10  2024 /usr/lib64/libunwind-x86_64.so.8.1.0*

**Comment by suprohub** [comment]
me helped: sudo ln -s /usr/lib/libunwind.so.8 /usr/lib/libunwind.so.1
