### ISSUE TITLE
Flood wait error

### ISSUE THREAD

**Issue by suprohub** [FedericoBruzzone/tdlib-rs#11]
Why i cant login in m accont from app?

i not unlogin like
    /*// Tell the client to close
    functions::close(CLIENT_ID.load(Ordering::Relaxed)).await.unwrap();

    // Handle the authorization state to wait for the "Closed" state
    handle_authorization_state(CLIENT_ID.load(Ordering::Relaxed), auth_rx, run_flag.clone()).await;

    // Wait for the previously spawned task to end the execution
    handle.await.unwrap();*/

but i think its not a problem for have this error

**Comment by FedericoBruzzone** [comment]
Please, can you export RUST_BACKTRACE=1 and provide me the errors?

**Comment by suprohub** [comment]
i wait and it works, but it strange
