### ISSUE TITLE
The historical chat messages obtained are incomplete

### ISSUE THREAD

**Issue by NPCDW** [FedericoBruzzone/tdlib-rs#3]
Hello, I am trying to make a function to export the messages of a channel to a table. This is the sample [google sheets](https://docs.google.com/spreadsheets/d/1O6dWMiyY0mDnecwWDso1QKlQQQYVqDFmb3Rrw2yLHQ4/edit?gid=0#gid=0) I made, but I found that two pieces of data were not obtained. After debugging in the program, I found that they were indeed not obtained. However, in the official client, these two records exist. The channel is [vpsliebiao](https://t.me/vpsliebiao) , and the two messages that were not obtained are [52](https://t.me/vpsliebiao/109) and [123](https://t.me/vpsliebiao/184) .

When I found this problem, I was using the tdlib library. After changing to tdlib-rs, the problem still exists.

**Comment by FedericoBruzzone** [comment]
Could you please provide the code you're using? This will help in understanding the issue better and finding a solution.

Thanks!

**Comment by FedericoBruzzone** [comment]
I understood your problem!

`messages.total_count` returns an approximate number of messages, not the exact number.
Here the docs: https://docs.rs/tdlib-rs/latest/tdlib_rs/types/struct.Messages.html
You should simply use the length of the messages you encountered.
Please let me know if this solves your problem. 😊


However, I advise you to continue using our library as it has a greater number of features and is constantly updated.

**Comment by NPCDW** [comment]
I am using your library, but the code has not been submitted yet.

I just used json to print it and found that this is an unsupported message type. Maybe I need to upgrade the version (1.8.19 -> 1.8.30 ?)

![image](https://github.com/FedericoBruzzone/tdlib-rs/assets/32638459/c8eedbdf-1f29-45ce-b3c3-2b34afc56737)

**Comment by FedericoBruzzone** [comment]
Ok, if this is the problem it can be solved. Are you able to tell me what kind of message it is? 
A screenshot would be great.

**Comment by NPCDW** [comment]
Here are screenshots of the two messages
![image](https://github.com/FedericoBruzzone/tdlib-rs/assets/32638459/8dd573ff-fd36-44e7-83bf-756e9227fde7)
![image](https://github.com/FedericoBruzzone/tdlib-rs/assets/32638459/544c9d13-5177-4bad-8330-7c73886385c4)

Below is the raw data of one of the messages
```json
{
    "id": 192937984,
    "sender_id": {
        "@type": "messageSenderChat",
        "chat_id": -1002240457608
    },
    "chat_id": -1002240457608,
    "sending_state": null,
    "scheduling_state": null,
    "is_outgoing": false,
    "is_pinned": false,
    "can_be_edited": false,
    "can_be_forwarded": false,
    "can_be_saved": true,
    "can_be_deleted_only_for_self": false,
    "can_be_deleted_for_all_users": false,
    "can_get_added_reactions": false,
    "can_get_statistics": false,
    "can_get_message_thread": false,
    "can_get_viewers": false,
    "can_get_media_timestamp_links": true,
    "can_report_reactions": false,
    "has_timestamped_media": true,
    "is_channel_post": true,
    "is_topic_message": false,
    "contains_unread_mention": false,
    "date": 1716937992,
    "edit_date": 1717977914,
    "forward_info": null,
    "interaction_info": {
        "view_count": 724,
        "forward_count": 6,
        "reply_info": null,
        "reactions": []
    },
    "unread_reactions": [],
    "reply_to": null,
    "message_thread_id": 0,
    "self_destruct_type": null,
    "self_destruct_in": 0.0,
    "auto_delete_in": 0.0,
    "via_bot_user_id": 0,
    "author_signature": "",
    "media_album_id": "0",
    "restriction_reason": "",
    "content": {
        "@type": "messageUnsupported"
    },
    "reply_markup": null
}
```

**Comment by FedericoBruzzone** [comment]
These messages are unsupported 'cause of the `quote` inside there.
Would you have time to fork the library and upgrade it to version `1.8.30`? if this is not the case we will try to update it as soon as possible.

**Comment by NPCDW** [comment]
let me try

**Comment by FedericoBruzzone** [comment]
> let me try

Don't worry, I'm doing it!

**Comment by FedericoBruzzone** [comment]
> let me try

There are problems with the build (in windows) of `tdlib` version 1.8.30. I'm trying to build version 1.8.29. It should already have this feature.

**Comment by NPCDW** [comment]
Thank you very much for your help, I tried version 1.0.3 and it solved that unsupported message type

**Comment by FedericoBruzzone** [comment]
No problems, it was a pleasure to help you. For anything contact us!🫶
