### ISSUE TITLE
support linux arm？

### ISSUE THREAD

**Issue by huangzulin** [FedericoBruzzone/tdlib-rs#6]
it support linux arm and arm64？

**Comment by FedericoBruzzone** [comment]
Yes, we support all versions if a TDLib for a specific target (including Linux ARM and ARM64) is already compiled in the system. 
Additionally, we are considering building the TDLib using GitHub Actions for these targets.

If I understand correctly it should be something like:
1. Install Git, clang >= 3.4, libc++, make, CMake >= 3.0.2, OpenSSL-dev, zlib-dev, gperf, PHP using your package manager
2. Run these commands in Bash to build TDLib and to install it to td/tdlib
```bash
export CROSS=/home/<name>/dev/arm/gcc-linaro-7.2.1/bin/arm-linux-gnueabihf
export CC=${CROSS}-gcc
export CXX=${CROSS}-g++

git clone https://github.com/tdlib/td.git
cd td

mkdir build_native
cd build_native
cmake ..
cmake --build . --target prepare_cross_compiling
cd ..

rm -rf build
mkdir build
cd build
cmake ..
CXXFLAGS="cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib .. -DCMAKE_CROSSCOMPILING=True
cmake --build . --target install
```

More info:
1. https://tdlib.github.io/td/build.html?language=Rust
2. https://github.com/tdlib/td/issues/49
